#ifndef __glxew_h__
#define __glxew_h__
#ifdef __cplusplus
extern "C" {
#endif
typedef void* PFNGLXCREATEWINDOWPROC;
typedef void* PFNGLXCREATEPIXMAPPROC;
typedef void* PFNGLXMAKECONTEXTCURRENTPROC;
typedef void* PFNGLXDELETEASSOCIATEDCONTEXTAMDPROC;
typedef void* PFNGLXMAKEASSOCIATEDCONTEXTCURRENTAMDPROC;
typedef void* PFNGLXCREATECONTEXTATTRIBSARBPROC;
typedef void* PFNGLXMAKECURRENTREADSGIPROC;
typedef void* PFNGLXGETTRANSPARENTINDEXSUNPROC;
typedef void* PFNGLXCREATENEWCONTEXTPROC;
typedef void* PFNGLXCREATEGLXPIXMAPMESAPROC;
typedef void* PFNGLXQUERYCURRENTRENDERERINTEGERMESAPROC;
typedef void* PFNGLXQUERYRENDERERINTEGERMESAPROC;
typedef void* PFNGLXGETSELECTEDEVENTPROC;
typedef void* PFNGLXGETSELECTEDEVENTSGIPROC;
typedef void* PFNGLXQUERYCONTEXTPROC;
typedef void* PFNGLXFREECONTEXTEXTPROC;
typedef void* PFNGLXCREATEASSOCIATEDCONTEXTAMDPROC;
typedef void* PFNGLXCREATEASSOCIATEDCONTEXTATTRIBSAMDPROC;
typedef void* PFNGLXGETACTIVEATTRIBARBPROC;
typedef void* PFNGLXQUERYRENDERERSTRINGMESAPROC;
typedef void* PFNGLXGETCURRENTCONTEXTPROC;
typedef void* PFNGLXGETCURRENTDISPLAYPROC;
typedef void* PFNGLXGETCURRENTREADDRAWABLEPROC;
#ifdef __cplusplus
}
#endif
#endif
